version: '3'
volumes:
    grafana.data:
        driver: local
        driver_opts:
            type: none
            device: /mnt/storage/grafana
            o: bind
    prometheus.data:
        driver: local
        driver_opts:
            type: none
            device: /mnt/storage/prometheus
            o: bind
services:
    proxy:
        image: nginx:1.17.9
        depends_on:
            - grafana
            - prometheus
        ports:
            - 80:80
        volumes:
            - ./nginx-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            static-network:
                ipv4_address: 172.22.0.2
    grafana:
        image: grafana/grafana
        volumes:
            - grafana.data:/var/lib/grafana
            - ./grafana:/etc/grafana
        networks:
            static-network:
                ipv4_address: 172.22.1.2
    prometheus:
        image: prom/prometheus
        restart: always
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus.data:/prometheus
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.external-url=http://192.168.0.118/monitor
            - --web.route-prefix=/
        networks:
            static-network:
                ipv4_address: 172.22.1.3
    cadvisor:
        image: google/cadvisor
        container_name: cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        networks:
            static-network:
                ipv4_address: 172.22.1.5
    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
        restart: always
        networks:
            static-network:
                ipv4_address: 172.22.1.6
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.22.0.0/16